### ISSUE TITLE
Can't setup with my API KEY

### ISSUE THREAD

**Issue by WolfganG1st** [CB0rghi/vscode-writer-ext#1]
When I try to setup the tool, I receive that error: **Command 'GPT Coder: Setup GPT Coder' resulted in an error (Unknown cypher)**

**Comment by ocodista** [comment]
Hello Felipe, thank you for creating this issue.

Please confirm to me What's the version of the extension and your current OS.

**Comment by WolfganG1st** [comment]
I'm using the v1.0.8

**Comment by ocodista** [comment]
Hey Felipe, I just released a new version 1.0.9 that should fix this issue for you.

Please let me know if it doesn't.

By the way, thank you for the review!
